apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 24h
  type: oci
  url: oci://ghcr.io/stefanprodan/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 1h
  chart:
    spec:
      chart: podinfo
      version: "6.5.*"
      sourceRef:
        kind: HelmRepository
        name: podinfo
  values:
    replicaCount: 2
